### ISSUE TITLE
Componente Shopping Cart - Configuracion Incorrecta en Add Component

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#13]
Cuando se agrega el componente Shopping Cart presionando el boton Add Component en una page, el componente se crea con los checkbox Edit y Form marcados. 
Esto genera el error common.apex.runtime.impl.ExecutionException: Invalid query: SELECT FROM null WHERE ID = :recordId al acceder a la pagina que contiene dicho componente. 

Cuando se crea la pagina Shopping Cart utilizando el modelo Shopping Cart de Plugin, el componente se crea solamente con el checkbox Edit marcado, y en este caso la pagina no falla. 

No hay forma de "desmarcar" el radio button Form para evitar el error.

**Comment by hugogmg** [comment]
Nota: revisar Confirguración del componente en pestaña plugin (org plugin) y revisar JS que tilda por defecto la vista (propio de cms revisar en org plugin)

**Comment by marianarush** [comment]
verificado ok
