### ISSUE TITLE
Configuracion de Profiles - Objetos que modifica Plugin

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#18]
**El profile de System Admin tienen que tener el field level security completo (view y edit) para todos estos objetos.** 

- [x] Component
- [x] Media
- [x] Member
- [x] Navigation
- [x] Post
- [x] Program: 
**- [x] RedemptionItem: Falta Read Access y Edit Access en campo Voucher Link**
**- [x] Reward: Falta Read Access y Edit Access en campo Category y Instructions Rich Text.** 
**- [x] Tag Item: Falta Read Access y Edit Access en campo Reward.** 

 **El profile Fielo Member Site tiene que tener los siguientes objetos:**

- [x] Account y Document: Read
- [x] Agreements: Read. View all fields	
- [x] Posts: Read. View all fields	
- [x] Categories: Read. View all fields	
- [x] Programs: Read. View all fields	
- [x] Components: Read. View all fields	
- [x] Redemptions: Read, Create, Edit. View y Edit all fields	
- [x] Components Library: Read. View all fields	
- [x] Redemption Items: Read, Create, Edit. View y Edit all fields	
- [x] Layouts: Read. View all fields	
- [x] Rewards: Read Edit. View all fields	
- [x] Media: Read. View all fields	
- [x] Reward Items: Read, Edit. View y Edit all fields	
- [x] Members: Read, Create, Edit. View y Edit all fields	
- [x] Sections: Read. View all fields	
- [x] Member Segments: Read. View all fields	
- [x] Segments: Read. View all fields	
- [x] Navigations: Read. View all fields	
- [x] Sites: Read. View all fields	
- [x] Pages: Read. View All fields	
- [x] Tags: Read. View all fields	
**- [x] Points: Read, Edit. View y Edit all fields.**  	
- [x] Transactions: Read. View all fields	

**Paginas del profile**
- [x] FieloCMS.Component	
- [x] FieloCMS.Logout	
- [x] FieloCMS.SiteConfig

**Comment by marianarush** [comment]
@diegoamarante deje en negrita lo que falta subir a los profiles

**Comment by marianarush** [comment]
Se deployo en una org de testing con cms y plt instalado y se verifico
- [ ] OK para System Admin
Para el profile Fielo Member Site falta:
- [x] Categories: Read en permisos. Field Level Security: View all fields
- [x] Media: Read en permisos. Field Level Security: View all fields
- [x] Posts: Read en permisos. Field Level Security: View all fields
- [x] Tags: Read en permisos. Field Level Security: View all fields

**Comment by diegoamarante** [comment]
Se agregaron los permisos para los objetos faltantes.
Ademas de Segment para Media y Post
