### ISSUE TITLE
El mail recibido cuando para continuar con la registracion no tiene un link

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#21]
En el mail llega FieloCMS__Page?memberId=a0H6A000001Qa1p&pageId=a0n6A000000LJN1 en vez de https://plugin102-developer-edition.na50.force.com/FieloCMS__Page?memberId=a0H6A000001Qa1p&pageId=a0n6A000000LJN1

**Comment by marianarush** [comment]
Esto pasa en la org de plugin, en estabilizacion no se reproduce.

**Comment by diegoamarante** [comment]
Es un tema de configuracion. El program tiene que tener el campo SiteURL completo sino no arma bien el link. En plugin no estaba, en estabilizacion no se reproduce en el program "Default", pero posiblemente ocurra en el program "Program 2"
