### ISSUE TITLE
Cambiar Modelo y componente de Catalog en Static Resource 

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#22]
El componente Catalog, en el view image tiene el campo FieloPLT__Image__c en lugar de FieloPLT__ExternalURL__c

Estoy hay que corregirlo tanto en el componente como en el modelo de catalog y actualizar el static resource.

**Comment by hugogmg** [comment]
@marianarush resuelto

**Comment by marianarush** [comment]
Verificado ok en org de testing estabilizacion 10.2
