### ISSUE TITLE
Componente My Profile - Comportamiento confuso

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#26]
Se modifica el name de un member, y al presionar el boton Submit, la botonera cambia y se agrega el boton Cancel (en un formato completamente distinto)
Si se presiona cancel, el componente pasa a renderizarse en otra seccion de la pagina. No vuelve a la seccion original hasta que se vuelve a ingresar en la misma.
Si se presiona submit, el cambio se realiza pero la pagina no se refresca y no cambian los botones.

**Comment by hugogmg** [comment]
@marianarush El componente Account estaba configurado como un Edit cuando es un View.
Y ese View luego usa la sub vista Form.

Voy a verificar si esta configuración esta correcta en el JSON

**Comment by hugogmg** [comment]
@marianarush Modifiqué el JSON para que esté como View

**Comment by marianarush** [comment]
Verificado ok en org de testing.

**Comment by marianarush** [comment]
Ok
