### ISSUE TITLE
FL-3555 - Import de JS y CSS por plugin

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#27]
Al activar el plugin, hay que completar los campos Plugin CSS y Plugin JavaScript del site con el static resource FieloPlugin_PlatformPlugin 
El workaround es completarlo a mano, llendo al static resource, view file, boton derecho, copiar direccion. y pegar a partir de /resource/1485179039000/FieloPlugin_PlatformPlugin

en caso de que no se pueda sistematizar, agregar en la documentacion, como ultimo paso despues del manual de instalacion de fielo plt + cms

**Comment by marianarush** [comment]
Revisar con @hugogmg:
- para que sirven los campos Plugin CSS y Plugin JavaScript
- Se podrian completar con varias URL? 
- Lo tendriamos que completar solo al activar el plugin de Fielo PLT - Fielo CMS? o para todos?
- Cuando se vuelve a deployar plugin, no se puede actualizar la url, en caso de que el static resource cambie. 
- Describir bien que se desarrollo, para que de ultima se pueda completar en la documentacion que modificar luego de un re deploy de plugin.

**Comment by hugogmg** [comment]
@marianarush @leoteren 

> para que sirven los campos Plugin CSS y Plugin JavaScript

Permite agregar las url de los static resources de aquellos plugins activados que tienen que ser cargados en el site

> Se podrian completar con varias URL?

Si, se deben completar con todos aquellos plugins activados

> Lo tendriamos que completar solo al activar el plugin de Fielo PLT - Fielo CMS? o para todos?

Debería completarse con todos los plugins activados

> Cuando se vuelve a deployar plugin, no se puede actualizar la url, en caso de que el static resource cambie.

Al deployar cualquier plugin hay que luego darle click al botón update.
Esa misma acción debería buscar su url en los campos Plugin CSS y Plugin JavaScript y actualizar el timestamp de su static resource. Tener en cuenta que solo debe actualizar el suyo ya que en estos campos pueden figurar mas de una url

Cualquier cosa preguntar

**Comment by marianarush** [comment]
@hugogmg como se identifica que static resource pertenece a cada plugin?

**Comment by hugogmg** [comment]
@marianarush @leoteren 
Por lo que vi, por ahora este proceso quedo manual.
Tengo entendido que cada Static Resource debería empezar de la forma FieloPlugin_NOMBREDELPLUGIN

Por ejemplo: FieloPlugin_PlatformPlugin
Quizás este nombre podría estar guardado en el static resource que definen los componentes que se instalan para así poder buscarlo

**Comment by marianarush** [comment]
Confirmado que solamente funciona la primera vez que se deploya. Despues el numero del static resource cambia, cuando se vuelve a redeployar.

**Comment by marianarush** [comment]
Tambien hay que corregir el archivo que es el FieloPlugin_PlatformPlugin

**Comment by leoteren** [comment]
Ahora los campos se cargan cuando se activa (inserta) o upgredea (edita) un plugin.

**Comment by marianarush** [comment]
verificado ok
