### ISSUE TITLE
FL-3578 - Validaciones en componente Register

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#28]
Al agregar un componente Register, los campos Account CRM Mode y Account CRM Owner y program tienen que ser obligatorios. 
Si no se completan, al intentar registrarse, el sitema cancela con Attemp to de reference a null object 
Tambien hay que agregar todas las validaciones de este componente que quedaron en FieloDEV. El bdd esta realizado en FieloDEV (Use case Configure Registration Component) 

Expected Result: 
Agregar una validacion para que no deje agregar un componente Register sin completar esos campos.

**Comment by gabrielfont** [comment]
https://fieloww.atlassian.net/browse/FL-3578

**Comment by marianarush** [comment]
Agregar que al momento de insertar el componente, se carguen valores por default para los tres campos:
Account - Standard Account
Owner: Select un system admin activo con Rol asignado
Program: El primero

Esto es para evitar que falle la creacion desde modelo.

**Comment by marianarush** [comment]
verificado ok en org de testing estabilizacion release 10.2
Al insertar el componente (ya sea desde la funcionalidad Add Component o desde Create Model) carga valores por default. 
Si el unico system admin no tiene rol, falla el insert con el mensaje



Al editarlo, si los campos se dejan vacios, muestra mensaje de error:
- Account CRM Mode: Must select a Mode.
- Account Owner: Must select an Owner.
- Program: Must select a Program.

Si el user seleccionado no tiene rol, muestra el mensaje
- Owner must have a Role.
