### ISSUE TITLE
FL-3908 - Modelo de Shopping Cart: No deja relacionadas las paginas shopping cart con redemption detail

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#30]
El modelo del shopping cart no crea las 2 paginas (shopping cart y redemption detail) relacionadas sino que las crea por separado. 
El JSON para la pagina Shopping Cart es este: 
{ "pages" : [ { "reference" : "a0e41000000xSa8AAE", "recordTypeName" : "Page", "Name" : "Shopping Cart", "FieloCMS__Icon__c" : "fielo-icon-content", "FieloCMS__Title__c" : "Shopping Cart", "sections" : [ { "FieloCMS__ElementType__c" : "Div", "FieloCMS__IsBody__c" : false, "FieloCMS__Order__c" : 12, "FieloCMS__Width__c" : "12", "subsections" : [ { "FieloCMS__ElementType__c" : "Div", "FieloCMS__IsBody__c" : false, "FieloCMS__Order__c" : 0, "FieloCMS__Width__c" : "12", "components" : [ { "reference" : "a0Y410000008IkkEAE", "recordTypeName" : "Widget", "componentLibrary" : "PlatformPlugin.ShoppingCart", "Name" : "Shopping Cart", "FieloCMS__Columns__c" : 2, "FieloCMS__Delay__c" : 2500, "FieloCMS__Desktop__c" : true, "FieloCMS__DetailParameter__c" : "id", "FieloCMS__FieldSet__c" : "[{\"required\":false,\"readOnly\":false,\"inlineHelpText\":\"\",\"placeholder\":\"\",\"autocomplete\":\"\",\"showLabel\":true,\"label\":\"Contract Name\",\"apiName\":\"Name\",\"type\":\"STRING\"}]]", "FieloCMS__IsAppMenu__c" : false, "FieloCMS__Layout__c" : "Edit", "FieloCMS__Limit__c" : 6, "FieloCMS__Mobile__c" : true, "FieloCMS__Order__c" : 1, "FieloCMS__Paging__c" : true, "FieloCMS__ParameterName__c" : "paginatorBinding", "FieloCMS__Rows__c" : 2, "FieloCMS__Tablet__c" : true, "FieloCMS__Width__c" : 0, "FilterBySegment__c" : false } ] } ] } ] } ] } 

El JSON para la pagina Redemption detail es este: 
{ "pages" : [ { "reference" : "a0e41000000xSa9AAE", "recordTypeName" : "Page", "Name" : "Redemption Detail", "FieloCMS__Icon__c" : "fielo-icon-content", "sections" : [ { "FieloCMS__ElementType__c" : "Div", "FieloCMS__IsBody__c" : false, "FieloCMS__Order__c" : 10, "FieloCMS__Width__c" : "12", "subsections" : [ { "FieloCMS__ElementType__c" : "Div", "FieloCMS__IsBody__c" : false, "FieloCMS__Order__c" : 11, "FieloCMS__Width__c" : "12", "components" : [ { "reference" : "a0Y410000008IklEAE", "recordTypeName" : "Record", "componentLibrary" : "PlatformPlugin.RedemptionDetail", "Name" : "Redemption Detail", "FieloCMS__Columns__c" : 2, "FieloCMS__Delay__c" : 2500, "FieloCMS__Desktop__c" : true, "FieloCMS__DetailParameter__c" : "id", "FieloCMS__FieldSet__c" : "[{\"type\":\"STRING\",\"apiName\":\"Name\",\"label\":\"Code\",\"showLabel\":true},{\"type\":\"PICKLIST\",\"apiName\":\"FieloPLT__Status__c\",\"label\":\"Status\",\"showLabel\":true},{\"type\":\"DOUBLE\",\"apiName\":\"FieloPLT__Points__c\",\"label\":\"Points\",\"showLabel\":true},{\"type\":\"DOUBLE\",\"apiName\":\"FieloPLT__TotalItems__c\",\"label\":\"Total Items\",\"showLabel\":true}]]", "FieloCMS__IsAppMenu__c" : false, "FieloCMS__LayoutMode__c" : "Post", "FieloCMS__Layout__c" : "View", "FieloCMS__Limit__c" : 6, "FieloCMS__Mobile__c" : true, "FieloCMS__Order__c" : 1, "FieloCMS__Paging__c" : true, "FieloCMS__ParameterName__c" : "paginatorBinding", "FieloCMS__Rows__c" : 2, "FieloCMS__Tablet__c" : true, "FieloCMS__Width__c" : 0, "FilterBySegment__c" : false }, { "reference" : "a0Y410000008IkmEAE", "recordTypeName" : "List", "componentLibrary" : "PlatformPlugin.RedemptionItems", "Name" : "Redemption Items", "FieloCMS__Columns__c" : 2, "FieloCMS__Delay__c" : 2500, "FieloCMS__Desktop__c" : true, "FieloCMS__DetailParameter__c" : "id", "FieloCMS__FieldSet__c" : "[{\"type\":\"REFERENCE\",\"apiName\":\"FieloPLT__RewardItem__c\",\"label\":\"Reward Item\",\"showLabel\":true,\"orderBy\":\"disabled\",\"linkToDetail\":false},{\"type\":\"DATE\",\"apiName\":\"FieloPLT__DeliveredDate__c\",\"label\":\"Delivered Date\",\"showLabel\":true,\"orderBy\":\"disabled\",\"linkToDetail\":false},{\"type\":\"DATE\",\"apiName\":\"FieloPLT__ExpirationDate__c\",\"label\":\"Expiration Date\",\"showLabel\":true,\"orderBy\":\"disabled\",\"linkToDetail\":false},{\"type\":\"PICKLIST\",\"apiName\":\"FieloPLT__Status__c\",\"label\":\"Status\",\"showLabel\":true,\"orderBy\":\"disabled\",\"linkToDetail\":false},{\"type\":\"STRING\",\"apiName\":\"FieloPLT__UniqueCode__c\",\"label\":\"Unique Code\",\"showLabel\":true,\"orderBy\":\"disabled\",\"linkToDetail\":false},{\"type\":\"STRING\",\"apiName\":\"VoucherLink__c\",\"label\":\"Voucher Link\",\"showLabel\":true,\"orderBy\":\"disabled\",\"linkToDetail\":false}]]", "FieloCMS__IsAppMenu__c" : false, "FieloCMS__Layout__c" : "Table", "FieloCMS__Limit__c" : 4, "FieloCMS__Mobile__c" : true, "FieloCMS__Order__c" : 2, "FieloCMS__Paging__c" : true, "FieloCMS__ParameterName__c" : "paginatorBinding", "FieloCMS__Rows__c" : 2, "FieloCMS__Tablet__c" : true, "FieloCMS__Width__c" : 0, "FilterBySegment__c" : false } ] } ] } ] } ] }

**Comment by gabrielfont** [comment]
No estan quedando relacionadas tampoco los componentes navigations con las navigations groups de los modelos de template.
Quedan relacionadas las paginas creadas por el modelo FAQ y de Catalog, pero no funciona en el site hasta que se refrescan esas paginas (en backend CMS)

**Comment by marianarush** [comment]
verificado ok
