### ISSUE TITLE
FL-3987 - Falta pagina Fielo Forgot Password en plugin

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#31]
Se elimino la pagina fielo forgot password porque no aportaba funcionalidad extra que la forgot password standard. 

El unico problema es que la forgot password standar no se visualiza con el mismo site template que tiene el site CMS. Siempre hay que hacer una pagina custom (que se hace siempre en las implementaciones) pero en el caso de no hacerla, se muestra la pantalla standard de salesforce, sin respetar el site template utilizado en el site cms y pareciendo ser un error.

**Comment by marianarush** [comment]
Se cierra ya que esta creado el issue FL-4277 como roadmap de ingenieria
