### ISSUE TITLE
FL-3913 - Limpiar cookie de shopping cart al registrarse

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#32]
Cuando el member se loguea, se limpia la cookie del shopping cart. 
Debe hacer lo mismo cuando se registra un nuevo member y se crea el user

**Comment by diegoamarante** [comment]
Lo probe en la org de desarrollo del Plugin y las cookies se inicializan cuando el usuario se loguea o se registra.
Verificar @nsoberon si hace lo mismo en el javascript cuando se loguea y cuando se registra.

**Comment by marianarush** [comment]
El error se reproduce.
Me logueo con un member y agrego un reward al shopping cart sin hacer checkout. Me deslogueo.
Me registro con otro member, y luego de completar las password, al quedar logueada en el site, voy al shopping cart y esta el reward agregado con el otro member.

**Comment by hugogmg** [comment]
Falto pushear el Static Resource en github

**Comment by marianarush** [comment]
verificado ok
