### ISSUE TITLE
FL-3919 - Voucher

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#33]
La pagina de voucher no renderiza la imagen de reward canjeado. 
Revisar funcionalidad de codigo de barra por codigo QR y que respete los parametros del program.

- Pasar CSS de Voucher

**Comment by hugogmg** [comment]
resuelto
![image](https://cloud.githubusercontent.com/assets/3833294/26688573/65bfd476-46c9-11e7-9eeb-5665b2124644.png)

**Comment by marianarush** [comment]
Verificado ok
