### ISSUE TITLE
Revisar campos Public Settings

### ISSUE THREAD

**Issue by diegoamarante** [Fielo-Plugins/fielocms-fieloee#34]
El campo ContactRelationshipClass__c se agrega y en el codigo no se hace referencia. Revisar todos los campos de Public Settings por que parece que se agregan dos veces.

**Comment by diegoamarante** [comment]
Se eliminaron los campos que agrega plugin del objeto PublicSettings

**Comment by marianarush** [comment]
Verificado ok en org de testing estabilizacion.
Se deployo desde Github y NO se crearon campos en el custom setting Public Settings
