### ISSUE TITLE
FL-4006 REQUIRED_FIELD_MISSING, Faltan campos obligatorios: [ProfileId]: [ProfileId]. al crear user

### ISSUE THREAD

**Issue by gabrielfont** [Fielo-Plugins/fielocms-fieloee#35]
We have a Test Class (TestCreateUser), we try to create a User running as the Site Guest User. The user that we need to create is a Customer Portal, and we are getting the following error: REQUIRED_FIELD_MISSING, Faltan campos obligatorios: [ProfileId]: [ProfileId]. I put some debugs and saw that the field is being populated, also I run the same test with an Admin user and the error is not showing. 
Also I saw that the apex class that is performing the action is "with sharing". If I change to "without sharing" and run as the Site Guest User the error is not showing. 
I need to now why we are getting the error when we try to create the user running with the guest user. On previous developments we could create a user running with the Site guest, but now we can`t. 
El issue fue solucionado cambiando la clase a without sharing, pero hay que volver a revisar el porque pasa.

**Comment by diegoamarante** [comment]
Se abrio un caso en SF, explicando lo que pasaba, simulando el escenario. La respuesta de SF es que con el usuario Guest no se pueden crear usuarios, no se le puede otorgar permisos sobre el User, por lo tanto la unica solucion que ya esta implementada por el proyecto de MasterMaq es la de que la clase tenga "without sharing".
