### ISSUE TITLE
Modelo de Shopping cart se crea sin Edit seteado y al ingresar al site no se visualiza correctamente

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#43]
- Al seleccionar el modelo de Shopping Cart, se crean dos paginas: 
- Una con el componente Shopping Cart y otra con el componente Redemption y Redemption Item.

el componente shopping cart se crea sin Layout edit, y en el site no se visualiza correctamente.

**Comment by nsoberon** [comment]
@marianarush Lo agregue al model, no se como verlo, asi que avisame cuando lo pruebes

**Comment by marianarush** [comment]
El error se sigue reproduciendo. Al crear una page con el modelo de shopping cart, no aparece tildado el edit

**Comment by marianarush** [comment]
verificado ok
