### ISSUE TITLE
Campos que tiene que agregar Plugin en PLT

### ISSUE THREAD

**Issue by marianarush** [Fielo-Plugins/fielocms-fieloee#5]
PROGRAM__UseAgreement__c se elimino de PLT y ahora lo agrega plugin. Este campo se tiene que querear para mostrar o no el agreement en caso que haya. Este campo se usaba en la clase AgreementCreateExtension para mostrar un warning en la creacion del agreement en caso que este campo estuviera en False.
REWARD__Instructions__c se elimino de PLT y lo tiene que agregar plugin. Este campo, si esta escrito, se muestra en el voucher

**Comment by sebastianclaros** [comment]
Creo que Agreement se iba a mover a un componente. Entonces la joda es que si pones el componente es que tiene agreement y queres la logica fuerte que tiene hoy. La flexibilidad que te daria es que si no podes el componente podes tener agreement igual pero sin la validacion en el template (un poco mas performante si no piensan cambiarlo nunca)
