### ISSUE TITLE
Error while deploying release v2.0.1

### ISSUE THREAD

**Issue by tibeal** [Fielo-Plugins/fielocms-fieloee#59]
When an org doesn't have any previous instalations of FieloCMS 1.75 several errors are displayed.

**_Note.:_** There is a workaround, if we install version 1.73 and upgrade it till 1.75 these errors do not appear.

**Failures:**
components/FieloCMSPLT_RegisterStep2.component(FieloCMSPLT_RegisterStep2):The specified Package Version number does not exist for that Package: FieloCMS, 1.73
components/FieloCMSPLT_ShoppingCart.component(FieloCMSPLT_ShoppingCart):The specified Package Version number does not exist for that Package: FieloCMS, 1.73
classes/FieloCMSPLT_RedemptionItemAPITest.cls(FieloCMSPLT_RedemptionItemAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionItemVouCtrl.cls(FieloCMSPLT_RedemptionItemVouCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionItemVouCtrlTest.cls(FieloCMSPLT_RedemptionItemVouCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionItemsSelector.cls(FieloCMSPLT_RedemptionItemsSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionItemsSelectorTest.cls(FieloCMSPLT_RedemptionItemsSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_Rewards.cls(FieloCMSPLT_Rewards):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectDescribe.cls(FieloCMSPLT_SObjectDescribe):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectDescribeTest.cls(FieloCMSPLT_SObjectDescribeTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionsSelector.cls(FieloCMSPLT_RedemptionsSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionsSelectorTest.cls(FieloCMSPLT_RedemptionsSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RegisterStep2Ctrl.cls(FieloCMSPLT_RegisterStep2Ctrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RegisterStep2CtrlTest.cls(FieloCMSPLT_RegisterStep2CtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RewardAPI.cls(FieloCMSPLT_RewardAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RewardAPITest.cls(FieloCMSPLT_RewardAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectDomain.cls(FieloCMSPLT_SObjectDomain):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectDomainTest.cls(FieloCMSPLT_SObjectDomainTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectSelector.cls(FieloCMSPLT_SObjectSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectSelectorTest.cls(FieloCMSPLT_SObjectSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectUnitOfWork.cls(FieloCMSPLT_SObjectUnitOfWork):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SObjectUnitOfWorkTest.cls(FieloCMSPLT_SObjectUnitOfWorkTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SecurityUtils.cls(FieloCMSPLT_SecurityUtils):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SecurityUtilsTest.cls(FieloCMSPLT_SecurityUtilsTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SegmentsSelectionCtrl.cls(FieloCMSPLT_SegmentsSelectionCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SegmentsSelectionCtrlTest.cls(FieloCMSPLT_SegmentsSelectionCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SelectMemberCtrl.cls(FieloCMSPLT_SelectMemberCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SelectMemberCtrlTest.cls(FieloCMSPLT_SelectMemberCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_UserCreation.cls(FieloCMSPLT_UserCreation):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_UserCreationTest.cls(FieloCMSPLT_UserCreationTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ShoppingCartCtrlTest.cls(FieloCMSPLT_ShoppingCartCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SiteLoginCtrl.cls(FieloCMSPLT_SiteLoginCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SiteLoginCtrlTest.cls(FieloCMSPLT_SiteLoginCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_SitesSelector.cls(FieloCMSPLT_SitesSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_StringBuilder.cls(FieloCMSPLT_StringBuilder):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_StringBuilderTest.cls(FieloCMSPLT_StringBuilderTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ToggleManagerCtrl.cls(FieloCMSPLT_ToggleManagerCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ToggleManagerCtrlTest.cls(FieloCMSPLT_ToggleManagerCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_TransactionAPI.cls(FieloCMSPLT_TransactionAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_TransactionAPITest.cls(FieloCMSPLT_TransactionAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ShoppingCartCtrl.cls-meta.xml:The specified Package Version number does not exist for that Package: FieloCMS, 1.73
classes/FieloCMSPLT_AgreementAPI.cls(FieloCMSPLT_AgreementAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_AgreementAcceptCtrl.cls(FieloCMSPLT_AgreementAcceptCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_AgreementsSelectorTest.cls(FieloCMSPLT_AgreementsSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BadgeAPI.cls(FieloCMSPLT_BadgeAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BadgeAPITest.cls(FieloCMSPLT_BadgeAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BadgeService.cls(FieloCMSPLT_BadgeService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BadgeServiceTest.cls(FieloCMSPLT_BadgeServiceTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_AgreementAcceptCtrlTest.cls(FieloCMSPLT_AgreementAcceptCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_AgreementsSelector.cls(FieloCMSPLT_AgreementsSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BarCodeCtrl.cls(FieloCMSPLT_BarCodeCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BarCodeCtrlTest.cls(FieloCMSPLT_BarCodeCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BlockUnblockMemberCtrl.cls(FieloCMSPLT_BlockUnblockMemberCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_BlockUnblockMemberCtrlTest.cls(FieloCMSPLT_BlockUnblockMemberCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ChangePwdCtrl.cls(FieloCMSPLT_ChangePwdCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ChangePwdCtrlTest.cls(FieloCMSPLT_ChangePwdCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_CheckoutCtrl.cls(FieloCMSPLT_CheckoutCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_CheckoutCtrlTest.cls(FieloCMSPLT_CheckoutCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_Components.cls(FieloCMSPLT_Components):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ComponentsLibrariesSelector.cls(FieloCMSPLT_ComponentsLibrariesSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ContactAPI.cls(FieloCMSPLT_ContactAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ContactAPITest.cls(FieloCMSPLT_ContactAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ContactService.cls(FieloCMSPLT_ContactService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ContactServiceTest.cls(FieloCMSPLT_ContactServiceTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_Exception.cls(FieloCMSPLT_Exception):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginAPI.cls(FieloCMSPLT_LoginAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginAsBackendCtrl.cls(FieloCMSPLT_LoginAsBackendCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginAsBackendCtrlTest.cls(FieloCMSPLT_LoginAsBackendCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginAsCtrl.cls(FieloCMSPLT_LoginAsCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_HandleInvitationsMbrCtrl.cls(FieloCMSPLT_HandleInvitationsMbrCtrl):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_HandleInvitationsMbrCtrlTest.cls(FieloCMSPLT_HandleInvitationsMbrCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginAsCtrlTest.cls(FieloCMSPLT_LoginAsCtrlTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginService.cls(FieloCMSPLT_LoginService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_LoginServiceTest.cls(FieloCMSPLT_LoginServiceTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MediaAPI.cls(FieloCMSPLT_MediaAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MediaService.cls(FieloCMSPLT_MediaService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MemberAPI.cls(FieloCMSPLT_MemberAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MemberAPITest.cls(FieloCMSPLT_MemberAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MemberService.cls(FieloCMSPLT_MemberService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MemberServiceTest.cls(FieloCMSPLT_MemberServiceTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MembersSelector.cls(FieloCMSPLT_MembersSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MembersSelectorTest.cls(FieloCMSPLT_MembersSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_MockupFactory.cls(FieloCMSPLT_MockupFactory):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_NavigationAPI.cls(FieloCMSPLT_NavigationAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_NavigationAPITest.cls(FieloCMSPLT_NavigationAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_NavigationService.cls(FieloCMSPLT_NavigationService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_NavigationServiceTest.cls(FieloCMSPLT_NavigationServiceTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_NavigationsSelector.cls(FieloCMSPLT_NavigationsSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_NavigationsSelectorTest.cls(FieloCMSPLT_NavigationsSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_OrganizationUtil.cls(FieloCMSPLT_OrganizationUtil):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_OrganizationUtilTest.cls(FieloCMSPLT_OrganizationUtilTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_Plugins.cls(FieloCMSPLT_Plugins):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_PostAPI.cls(FieloCMSPLT_PostAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_PostAPITest.cls(FieloCMSPLT_PostAPITest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_PostService.cls(FieloCMSPLT_PostService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_PostServiceTest.cls(FieloCMSPLT_PostServiceTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ProgramService.cls(FieloCMSPLT_ProgramService):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_Programs.cls(FieloCMSPLT_Programs):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ProgramsSelector.cls(FieloCMSPLT_ProgramsSelector):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_ProgramsSelectorTest.cls(FieloCMSPLT_ProgramsSelectorTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_QueryFactory.cls(FieloCMSPLT_QueryFactory):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_QueryFactoryTest.cls(FieloCMSPLT_QueryFactoryTest):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionAPI.cls(FieloCMSPLT_RedemptionAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
classes/FieloCMSPLT_RedemptionItemAPI.cls(FieloCMSPLT_RedemptionItemAPI):core.apexpages.quickfix.QuickFixException: Component c:fielocmsplt_registerstep2 does not exist
profiles/Admin.profile(Admin):In field: apexClass - no ApexClass named FieloCMSPLT_MemberAPI found
profiles/Fielo Member Site.profile(Fielo Member Site):In field: apexClass - no ApexClass named FieloCMSPLT_MemberAPI found

**Comment by apolo88** [comment]
fixed on version 2.0.2
